server:
  port: 9000

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Gotcha-Getcha/gotcha-backend
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health,info,env
